name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: apt update && apt install -y python3-pip && pip install pipenv

      - name: Install mani dependencies
        run: pipenv install --dev

      - name: ✅ Run mani tests
        run: pipenv run test

      - name: Install tic_tac_toe-fat_effect_handlers example dependencies
        working-directory: ./examples/tic_tac_toe-fat_effect_handlers/backend
        run: pipenv install --dev

      - name: ✅ Run tic_tac_toe-fat_effect_handlers example tests
        working-directory: ./examples/tic_tac_toe-fat_effect_handlers/backend
        run: pipenv run test
