name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Install mani dependencies
        run: pipenv install --dev

      - name: ✅ Run mani tests
        run: pipenv run test

      - name: Install fat example dependencies
        run: pipenv install --dev
        working-directory: ./examples/tic_tac_toe-fat_effect_handlers

      - name: ✅ Run fat example tests
        run: pipenv run test
        working-directory: ./examples/tic_tac_toe-fat_effect_handlers
