name: CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y python3-pip && sudo pip install pipenv

      - name: Install mani dependencies
        run: pipenv install --dev

      - name: ✅ Run mani tests
        run: pipenv run test
